# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-14 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webtreasures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(db_column=b'goods_code', default=b'', max_length=100, verbose_name='\u5546\u54c1\u7f16\u7801')),
                ('money_amount', models.FloatField(db_column=b'money_amount', default=0.0, verbose_name='\u6536\u5165\u91d1\u989d')),
                ('type_code', models.CharField(db_column=b'type_code', max_length=100, verbose_name='\u6536\u5165\u7c7b\u578b')),
                ('income_date', models.DateTimeField(db_column=b'income_date', default=django.utils.timezone.now, verbose_name='\u5165\u8d26\u65e5\u671f')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6570\u636e\u521b\u5efa\u65e5\u671f')),
                ('mod_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65e5\u671f')),
                ('logic_del', models.IntegerField(db_column=b'logic_del', default=0, verbose_name='\u903b\u8f91\u5220\u9664')),
            ],
            options={
                'db_table': 'income_detail',
                'verbose_name': '\u6536\u5165\u660e\u7ec6',
                'verbose_name_plural': '\u6536\u5165\u660e\u7ec6',
            },
        ),
    ]
