# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtreasures', '0002_incomedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(db_column=b'goods_code', default=b'', max_length=100, unique=True, verbose_name='\u5546\u54c1\u7f16\u7801')),
                ('fashion_style', models.CharField(db_column=b'fashion_style', default=b'', max_length=100, verbose_name='\u670d\u88c5\u6b3e\u5f0f')),
                ('sell_status', models.IntegerField(db_column=b'sell_status', default=0, verbose_name='\u5356\u51fa\u72b6\u6001')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6570\u636e\u521b\u5efa\u65e5\u671f')),
                ('mod_date', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65e5\u671f')),
                ('logic_del', models.IntegerField(db_column=b'logic_del', default=0, verbose_name='\u903b\u8f91\u5220\u9664')),
            ],
            options={
                'db_table': 'goods_info',
                'verbose_name': '\u670d\u88c5\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u88c5\u4fe1\u606f',
            },
        ),
    ]
